export interface TiskilistaDetailDto {
  readonly id: string;
  readonly osoite: string;
  readonly postinumero: string | null;
  readonly postitoimipaikka: string | null;
  readonly tyyppi: string | null;
  readonly vuokra: number | null;
  readonly vapautuu: string | null;
  readonly poismuutto: string | null;
  readonly remonttiAlkaa: string | null;
  readonly remonttiPaattyy: string | null;
  readonly neliot: number | null;
  readonly kerros: string | null;
  readonly kerroksia: string | null;
  readonly tila: string | null;
  readonly sopimusTila: string | null;
  readonly kunta: string | null;
  readonly kaupunginosa: string | null;
  readonly markkinointialue: string | null;
  readonly lumoFi: boolean;
  readonly vuokraovi: boolean;
  readonly onKuvausTarve: boolean;
  readonly muistio: string | null;
  readonly kuvaus: string | null;
  readonly lisaTieto: string | null;
  readonly hissi: boolean;
  readonly parveke: boolean;
  readonly sauna: boolean;
  readonly yhteissaUna: boolean;
  readonly vesimittaus: boolean;
  readonly pesula: boolean;
  readonly astianpesukone: boolean;
  readonly aluetoimisto: string | null;
  readonly latitude: number | null;
  readonly longitude: number | null;
  readonly lumoUrl: string | null;
}
