@mVasu.Api_HostAddress = https://localhost:7216

### Health check (anonyymi)
GET {{mVasu.Api_HostAddress}}/api/health
Accept: application/json

###

### OpenAPI document (development only)
GET {{mVasu.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###
